name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build
        run: npm run build

      # Copy built files and compose config to VM
      - name: Upload dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/,compose.yml,docker/"
          target: "/tmp/strudal/"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo rm -rf /strudal/dist /strudal/docker /strudal/compose.yml
            sudo mv /tmp/strudal/dist /strudal/dist
            sudo mv /tmp/strudal/docker /strudal/docker
            sudo mv /tmp/strudal/compose.yml /strudal/compose.yml
            sudo rm -rf /tmp/strudal
            cd /strudal
            sudo docker-compose up -d --pull always --remove-orphans